Resources:
  EpisodesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "PodcastReviewService-Episodes"
      AttributeDefinitions:
        - AttributeName: "podcast"
          AttributeType: "S"
        - AttributeName: "episodeNr"
          AttributeType: "N"
        - AttributeName: "avgRating"
          AttributeType: "N"
        - AttributeName: "episodeId"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "podcast"
          KeyType: "HASH"
        - AttributeName: "episodeNr"
          KeyType: "RANGE"
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        - IndexName: "TopRatedEpisodesIndex"
          KeySchema:
            - AttributeName: "avgRating"
              KeyType: "HASH"
            - AttributeName: "episodeId"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "ALL"
