@startuml
'https://plantuml.com/sequence-diagram

autonumber

Client -> "Website Add Review Page": Submit add review form
"Website Add Review Page" -> AddReviewActivity :Add Review request
AddReviewActivity-> reviews: Save review



@enduml