@startuml
'https://plantuml.com/sequence-diagram

autonumber
Client -> "Website Top-Rated Page": Submit get top-rated form
"Website Top-Rated Page" -> GetTopRatedActivity : Get top-rated request
GetTopRatedActivity-> episodes: get episodes

episodes -> GetTopRatedActivity: episode
GetTopRatedActivity -> "Website Top-Rated Page" : List<Episodes>
"Website Top-Rated Page" -> Client : list of episodes
@enduml